server {
    listen 0.0.0.0:8080;

    error_page 500 502 503 504 /www/default_error.html;
    error_page 403 404 413 /www/default_error.html;

    client_max_body_size 4M;

    location / {
        methods GET POST;
        root /www;
        index default_index.html;
        autoindex on;
    }

    location /static {
        methods GET;
        root /www;
        autoindex on;
    }

    location /old-page {
        return 301 /;
    }

    location /uploads {
        methods GET POST DELETE;
        root /www;
        upload_store /www/uploads/;
    }

    location /cgi-bin {
        methods GET POST;
        root /www;
        cgi_pass .bash /bin/bash;
        cgi_pass .php /usr/bin/php-cgi;
    }
}
