server {
    listen 127.0.0.1:8080;

    error_page 500 502 503 504 /errors/50x.html;
    error_page 404 /errors/404.html;

    client_max_body_size 15G;

    location / {
        methods GET POST;
        root /var/www/html;
        index index.html;
        autoindex off;
    }

    location /static {
        methods GET;
        root /var/www/static;
        autoindex on;
    }

    location /old-page {
        return 301 /new-page;
    }

    location /uploads {
        methods POST DELETE;
        root /var/www/uploads;
        upload_store /var/www/uploads/tmp;
    }

    location /cgi-bin {
        methods GET POST;
        root /var/www/cgi-bin;
        cgi_pass .php /usr/bin/php-cgi;
    }
}
